name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: docker
    steps:
      - name: Set Node.js 20.x
        uses: https://github.com/actions/setup-node@v3
        with:
	      node-version: 20.x
	  - name: Run install
	    uses: borales/actions-yarn@v4
	    with:
	      cmd: install
	  - name: Build production bundle
	    uses: borales/actions-yarn@v4
	    with:
	      cmd: build
